### ISSUE TITLE
Support old versions of rails

### ISSUE THREAD

**Issue by kirillshevch** [woodcrust/novaposhta#2]
Why do we need activesupport 5+, maybe we can remove version from gemspec for add ability to use with old version of rails?
[https://github.com/woodcrust/novaposhta/blob/master/novaposhta.gemspec#L31](url)

**Comment by nerzh** [comment]
ok [this](https://github.com/woodcrust/novaposhta/commit/183f9925a0a5ed1af7d57ddfd0a0af82bb33936d)

**Comment by kirillshevch** [comment]
@woodcrust great!
